services:
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:3306
    volumes:
      - db:/var/lib/mysql

  cache:
    image: redis:7.4-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data

  app:
    image: note-taking-api
    depends_on:
      - db
      - cache
    environment:
      - PORT=${PORT}
      - DATABASE_HOST=db
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - JWT_ACCESS_TOKEN_SECRET=${JWT_ACCESS_TOKEN_SECRET}
      - JWT_ACCESS_TOKEN_EXPIRES_IN=${JWT_ACCESS_TOKEN_EXPIRES_IN}
      - JWT_REFRESH_TOKEN_SECRET=${JWT_REFRESH_TOKEN_SECRET}
      - JWT_REFRESH_TOKEN_EXPIRES_IN={JWT_REFRESH_TOKEN_EXPIRES_IN}
      - REDIS_URL=cache
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - ${PORT}:5000

volumes:
  db:
    driver: local
  cache:
    driver: local